const WORDS = [
    // A
    "able", "about", "above", "abroad", "absence", "absent", "absolute", "abstract", "abuse", "accept", "access",
    "accident", "account", "accurate", "achieve", "across", "action", "active", "activity", "actually", "addition",
    "address", "admit", "adopt", "adult", "advance", "advice", "affect", "afraid", "after", "afternoon", "again",
    "against", "agree", "ahead", "alarm", "album", "alert", "alive", "allow", "almost", "alone", "along", "already",
    "also", "although", "always", "among", "anger", "angle", "animal", "answer", "apart", "apply", "area", "argument",
    "around", "arrange", "arrest", "arrive", "article", "aside", "aspect", "attack", "attempt", "attention", "attitude",
    "attract", "authority", "available", "avoid", "award", "aware", "away", "awful",
    // B
    "back", "background", "balance", "basic", "basis", "battle", "beautiful", "because", "become", "before", "began",
    "begin", "behavior", "being", "believe", "below", "benefit", "between", "beyond", "birth", "black", "block",
    "blood", "blue", "board", "body", "book", "born", "both", "bottom", "brain", "break", "brief", "bring", "broad",
    "broke", "brown", "build", "built", "busy", "button", "buyer",
    // C
    "call", "came", "care", "carry", "case", "cause", "cell", "center", "certain", "chance", "change", "character",
    "charge", "check", "child", "choice", "choose", "civil", "claim", "class", "clean", "clear", "close", "cold",
    "collect", "color", "come", "common", "community", "company", "compare", "complete", "concern", "condition",
    "conflict", "consider", "contain", "continue", "control", "copy", "correct", "cost", "could", "country", "couple",
    "course", "cover", "create", "crime", "cross", "culture", "current", "customer",
    // D
    "dark", "data", "dead", "deal", "death", "decide", "deep", "defense", "define", "degree", "deliver", "demand",
    "describe", "design", "develop", "difference", "difficult", "direct", "discover", "discuss", "distance", "does",
    "done", "door", "doubt", "down", "draw", "dream", "drive", "drop", "drug", "during",
    // E
    "each", "early", "earth", "east", "easy", "edge", "education", "effect", "effort", "either", "election", "else",
    "energy", "enjoy", "enough", "enter", "entire", "equal", "error", "escape", "establish", "event", "ever", "every",
    "evidence", "evil", "exact", "example", "exist", "expect", "experience", "explain", "express", "extra",
    // F
    "face", "fact", "fail", "fall", "false", "family", "father", "fear", "feel", "field", "fight", "figure", "fill",
    "film", "final", "find", "fire", "first", "five", "flat", "floor", "focus", "follow", "food", "force", "foreign",
    "form", "forward", "found", "four", "free", "from", "front", "full", "function", "future",
    // G
    "game", "general", "girl", "give", "glad", "glass", "goal", "goes", "good", "government", "grand", "great",
    "green", "ground", "group", "grow", "growth", "guess", "guide", "guilty",
    // H
    "half", "hand", "happen", "hard", "have", "head", "health", "hear", "heart", "heavy", "help", "here", "high",
    "history", "hold", "home", "hope", "hour", "huge", "human",
    // I
    "idea", "identify", "image", "impact", "important", "include", "increase", "indeed", "indicate", "individual",
    "industry", "information", "inside", "instead", "interest", "involve", "issue", "item",
    // J
    "join", "judge", "just", "justice",
    // K
    "keep", "kill", "kind", "know", "knowledge",
    // L
    "lack", "land", "language", "large", "last", "late", "lead", "learn", "leave", "legal", "less", "level", "life",
    "light", "likely", "line", "list", "live", "local", "long", "look", "lose", "loss", "love",
    // M
    "main", "make", "management", "many", "mark", "market", "matter", "mean", "media", "meet", "method", "middle",
    "might", "military", "mind", "miss", "model", "modern", "moment", "money", "month", "more", "morning", "most",
    "move", "much", "must",
    // N
    "name", "national", "natural", "near", "need", "network", "never", "news", "next", "night", "none", "normal",
    "north", "note", "nothing", "notice", "number",
    // O
    "object", "offer", "often", "once", "only", "open", "option", "order", "other", "over", "owner",
    // P
    "paper", "parent", "part", "party", "pass", "past", "path", "peace", "people", "perhaps", "period", "person",
    "phone", "picture", "piece", "place", "plan", "plant", "play", "point", "police", "policy", "political",
    "position", "possible", "power", "practice", "present", "pressure", "price", "probably", "problem", "process",
    "produce", "program", "provide", "public", "pull", "push",
    // Q
    "quality", "question", "quickly", "quite",
    // R
    "race", "raise", "reach", "read", "ready", "real", "reason", "receive", "recent", "record", "reduce", "relate",
    "remain", "remember", "report", "require", "research", "result", "return", "reveal", "right", "rise", "road",
    "role", "room", "rule",
    // S
    "safe", "same", "save", "scene", "school", "science", "seek", "seem", "sense", "serve", "seven", "share", "show",
    "side", "sign", "similar", "simple", "since", "situation", "size", "skill", "small", "social", "some", "sort",
    "south", "space", "speak", "special", "spend", "stand", "start", "state", "stay", "step", "still", "stop",
    "store", "story", "street", "strong", "study", "subject", "support", "sure", "system",
    // T
    "table", "take", "talk", "task", "team", "tell", "term", "test", "than", "that", "their", "them", "then", "there",
    "they", "thing", "think", "this", "those", "though", "thought", "thousand", "through", "time", "today",
    "together", "toward", "town", "trade", "traditional", "tree", "true", "trust", "truth", "turn", "type",
    // U
    "under", "understand", "union", "unit", "until", "upon", "used", "user",
    // V
    "value", "various", "very", "view", "violence", "voice", "vote",
    // W
    "walk", "want", "warn", "watch", "water", "week", "well", "west", "what", "when", "where", "whether", "which",
    "while", "white", "wide", "will", "wind", "wish", "with", "within", "without", "woman", "word", "work", "world",
    "worry", "would", "write", "wrong",
    // Y-Z
    "yard", "year", "young", "your", "zero", "zone",
    // Extended batch 1
    "abandon", "ability", "aboard", "abolish", "absorb", "accent", "acclaim", "accomplish", "acquire", "adapt",
    "adequate", "adjacent", "adjust", "administer", "admire", "adolescent", "advantage", "adventure", "advertise",
    "advocate", "afford", "agent", "aggression", "agile", "aging", "aircraft", "alcohol", "alias", "align", "alleged",
    "allocate", "alter", "ambition", "amend", "ample", "analyze", "ancient", "announce", "annual", "anticipate",
    "anxiety", "apologize", "appeal", "appear", "applaud", "apple", "appoint", "appreciate", "approach", "approve",
    "archive", "arise", "armor", "army", "assert", "assess", "assist", "associate", "assume", "assure", "atmosphere",
    "attach", "attain", "attend", "audit", "author", "automatic", "average", "avid", "awake", "badge", "ballot",
    "barely", "barrier", "batch", "beach", "beard", "beast", "behave", "belong", "beneath", "beside", "better",
    "bicycle", "bitter", "blame", "blank", "blast", "bleed", "blend", "bless", "blind", "blink", "bloom", "blown",
    "blueprint", "blunt", "bold", "bomb", "bond", "bonus", "boost", "border", "bother", "bounce", "brave", "breach",
    "breed", "brick", "bridge", "bright", "bronze", "brother", "budget", "bullet", "bundle", "burden", "burst",
    "cabin", "calculate", "calendar", "campaign", "cancel", "canvas", "capture", "carbon", "career", "castle",
    "catch", "cattle", "ceiling", "celebrate", "chain", "chair", "chalk", "channel", "chart", "chase", "chief",
    "circle", "citizen", "climb", "clock", "cloud", "coach", "coast", "coffee", "column", "combine", "commit",
    "communicate", "compete", "compile", "complex", "compute", "concept", "connect", "consent", "consist",
    "construct", "consult", "convert", "convince", "cooperate", "council", "courage", "craft", "crash", "crazy",
    "creek", "crew", "cricket", "crisis", "critic", "crowd", "crucial", "cruel", "crush", "cycle", "daily", "dance",
    "danger", "debate", "decade", "decline", "defeat", "delay", "delegate", "deny", "depend", "deploy", "deserve",
    "detail", "detect", "device", "diagnose", "dialogue", "diet", "differ", "digital", "dilemma", "dimension",
    "discipline", "display", "distinct", "distribute", "divide", "document", "domain", "draft", "drain", "dramatic",
    "dress", "drift", "drink", "drown", "dynamic", "eager", "earn", "elect", "element", "elite", "emerge", "emotion",
    "employ", "enable", "encourage", "enhance", "enormous", "ensure", "evaluate", "evolve", "examine", "exceed",
    "exchange", "execute", "exercise", "exhibit", "expand", "expose", "extend", "extreme", "fabric", "facility",
    "factor", "faith", "fame", "fancy", "fashion", "feature", "federal", "fence", "fetch", "fierce", "filter",
    "finish", "fiscal", "flame", "fleet", "flesh", "float", "flood", "flower", "fluid", "flush", "foam", "forest",
    "formal", "formula", "fortune", "fossil", "fraction", "fragment", "frame", "frank", "fraud", "fresh", "friend",
    "fruit", "fully", "fund", "funny", "gather", "gauge", "gender", "gentle", "genuine", "ghost", "giant", "globe",
    "gloom", "glory", "glove", "golden", "grace", "grant", "grasp", "grave", "greet", "grief", "grill", "grind",
    "groan", "gross", "grove", "guard", "guilt", "habit", "handle", "harbor", "harvest", "haste", "hence", "heritage",
    "hidden", "honor", "horizon", "hostile", "humble", "humor", "hunger", "hunt", "ideal", "ignore", "illegal",
    "imagine", "immense", "impose", "improve", "impulse", "income", "index", "infant", "inflict", "inject", "inner",
    "innocent", "input", "inspect", "inspire", "install", "intense", "intent", "invest", "island", "jacket",
    "jealous", "journal", "journey", "junior", "label", "labor", "launch", "layer", "leader", "least", "lemon",
    "limit", "listen", "logic", "loyal", "magic", "major", "manage", "manner", "margin", "master", "match", "mature",
    "maximum", "measure", "mentor", "merge", "merit", "message", "minor", "miracle", "mission", "mistake", "mixture",
    "modify", "monitor", "moral", "mostly", "motion", "motivate", "mount", "multiple", "mutual", "narrow", "nation",
    "nature", "negative", "neither", "nerve", "neutral", "noble", "noise", "novel", "nurse", "observe", "obtain",
    "occur", "officer", "okay", "operate", "oppose", "outcome", "output", "overcome", "overlook", "package", "panel",
    "passion", "patient", "pattern", "pause", "perform", "permit", "pilot", "plain", "platform", "please", "pledge",
    "plenty", "plot", "pocket", "positive", "potential", "prefer", "prepare", "prevent", "primary", "prime",
    "principle", "priority", "private", "profit", "project", "promote", "proper", "protect", "prove", "purpose",
    "random", "range", "rapid", "ratio", "react", "rebuild", "recruit", "reform", "refuse", "region", "reject",
    "release", "relief", "rely", "remove", "repair", "replace", "request", "rescue", "resist", "resolve", "resource",
    "respond", "restore", "revenue", "review", "reward", "rhythm", "rigid", "risk", "rival", "rough", "scale",
    "scope", "secure", "select", "senior", "sequence", "settle", "severe", "shift", "signal", "silent", "silver",
    "single", "solve", "source", "stable", "stage", "standard", "status", "steady", "steel", "stock", "storm",
    "strategy", "stress", "stretch", "strict", "struggle", "submit", "succeed", "sudden", "suffer", "suggest",
    "summer", "supply", "surface", "survey", "survive", "symbol", "target", "teach", "technique", "temporary",
    "tend", "tension", "theory", "threat", "threshold", "throw", "tight", "title", "token", "total", "touch", "trace",
    "track", "train", "transfer", "transform", "travel", "treat", "trend", "trial", "trigger", "trouble", "typical",
    "ultimate", "unique", "update", "upgrade", "urban", "usual", "utility", "valid", "verify", "version", "vessel",
    "vital", "vocal", "waste", "wealth", "weapon", "weight", "welfare", "whole", "whose", "winter", "witness",
    "wonder", "worthy", "yield",
    // Extended batch 2
    "abide", "abrupt", "absurd", "abyss", "ache", "acid", "acorn", "acoustic", "acrobat", "actor", "acute", "adept",
    "adhere", "adobe", "adore", "adrift", "aerial", "affront", "afoot", "aghast", "agony", "aide", "ailment",
    "aimless", "aisle", "ajar", "akin", "alas", "albeit", "alder", "aloft", "alumni", "amaze", "amber", "amble",
    "amiable", "amiss", "amuse", "anchor", "anew", "ankle", "annex", "annoy", "antic", "anvil", "aorta", "appease",
    "aptly", "arbor", "ardent", "ardor", "arid", "arouse", "arson", "artful", "ascend", "ashen", "askew", "aspire",
    "assail", "astute", "atone", "attic", "augment", "austere", "avenge", "avert", "babble", "baffled", "baking",
    "balcony", "banter", "bargain", "baron", "bathe", "beckon", "befall", "behold", "belief", "beloved", "bestow",
    "bewail", "beware", "bewilder", "birch", "blaze", "bleak", "blight", "bliss", "bluster", "boggle", "bolster",
    "bonfire", "bottle", "brawl", "breezy", "brisk", "bristle", "brittle", "brood", "bruise", "brunt", "brutal",
    "bubble", "bumble", "burrow", "bustle", "cackle", "calamity", "calm", "candid", "canopy", "capable", "captive",
    "carve", "casual", "caution", "cavern", "cease", "chafe", "chant", "charm", "chasm", "cheer", "cherish", "chide",
    "chisel", "chorus", "clamp", "clamor", "clarity", "clash", "cling", "cloak", "coarse", "cobble", "coerce", "coil",
    "collapse", "comet", "compose", "conceal", "confine", "confuse", "contend", "convey", "coral", "corner", "covert",
    "cozy", "cramp", "craze", "creak", "credible", "crest", "crisp", "crumble", "cunning", "curb", "curious",
    "curtain", "custom", "dagger", "dainty", "dangle", "daring", "darken", "daunt", "dazzle", "deadly", "debris",
    "decay", "deceit", "deepen", "defiant", "delight", "deluge", "dense", "descend", "devote", "devour", "discern",
    "dismal", "displace", "disrupt", "distant", "distort", "divert", "dizzy", "docile", "dodge", "doleful",
    "drastic", "dreary", "dwindle", "earnest", "eerie", "elaborate", "eminent", "endure", "engulf", "enrage",
    "enslave", "envious", "erode", "errant", "eternal", "evade", "exert", "exile", "exult", "faint", "fallen",
    "fallow", "famine", "fanatic", "fathom", "faulty", "feeble", "fervent", "filth", "flair", "flare", "flaw",
    "flicker", "flinch", "flock", "flourish", "fluctuate", "flutter", "foil", "folly", "forage", "forbid", "forlorn",
    "forsake", "foster", "frantic", "frugal", "fulfill", "furious", "furtive", "gallant", "garble", "garish",
    "garner", "gaunt", "gaze", "giddy", "gleam", "glide", "glimmer", "gloomy", "glorious", "glower", "gnaw", "gorge",
    "govern", "gracious", "grapple", "gratify", "grim", "grimace", "gripe", "gritty", "grumble", "guile", "gulch",
    "gust", "haggard", "hamper", "hardy", "harsh", "haunt", "havoc", "haze", "herald", "hinder", "hollow", "honest",
    "horror", "hover", "hurtle", "hustle", "ignite", "imminent", "impede", "implore", "impure", "inert", "infuse",
    "inhale", "injure", "insult", "intrude", "invoke", "irate", "jagged", "jostle", "jumble", "keen", "kindle",
    "kneel", "lament", "lapse", "lash", "latch", "laud", "lavish", "linger", "listless", "lofty", "loiter", "loom",
    "lunge", "lurk", "malice", "mantle", "marvel", "mellow", "menace", "meager", "mend", "meander", "mimic", "mingle",
    "mire", "moan", "mock", "modest", "molten", "mourn", "murky", "muster", "naive", "neglect", "nourish", "nurture",
    "obscure", "offend", "ominous", "opaque", "ordeal", "oust", "outrage", "pacify", "parch", "pardon", "peril",
    "persist", "petty", "pierce", "plight", "plunge", "plunder", "poignant", "ponder", "portend", "potent", "pounce",
    "precede", "precise", "presume", "prevail", "probe", "profound", "prolong", "prompt", "prone", "prosper",
    "prowl", "prudent", "purge", "pursue", "quake", "qualm", "quest", "quiver", "radiant", "ramble", "rampant",
    "ransack", "ravage", "reckless", "recoil", "redeem", "relent", "remorse", "renounce", "repel", "repent",
    "resilient", "restless", "retaliate", "retreat", "revere", "revolt", "rouse", "ruin", "ruthless", "savage",
    "scatter", "scorch", "scorn", "seize", "serene", "shatter", "shelter", "shroud", "siege", "simmer", "sinister",
    "skeptical", "slander", "slumber", "smolder", "solemn", "somber", "sorrow", "spark", "spiral", "splendor",
    "squander", "stagger", "stain", "stark", "startle", "steadfast", "stealthy", "stern", "stifle", "strain",
    "stride", "strife", "subdue", "subtle", "surge", "swindle", "taunt", "tempest", "tenacious", "tense", "terrify",
    "thrive", "torment", "totter", "tremble", "tumult", "unravel", "unrest", "unstable", "uproar", "urge", "valor",
    "vanish", "vehement", "vengeance", "vile", "vindicate", "vulnerable", "wander", "wary", "weary", "wield",
    "wither", "wrath", "yearn", "zealous",
    // Extended batch 3
    "aboard", "accent", "achieve", "acquire", "adequate", "adjust", "adore", "afford", "agent", "alarm", "alias",
    "align", "allow", "alter", "amaze", "angel", "annex", "apply", "arena", "argue", "armor", "array", "arrow",
    "asset", "attach", "audit", "avoid", "awake", "bake", "band", "bank", "banner", "bare", "barn", "base", "bath",
    "beam", "bear", "beat", "bench", "bind", "bite", "blade", "bland", "blend", "bloom", "blow", "blur", "boast",
    "bolt", "bone", "bore", "bound", "brace", "brand", "brew", "brisk", "brush", "bulk", "bump", "bunch", "burn",
    "cage", "calm", "camp", "cape", "card", "cart", "cast", "cave", "chalk", "cheat", "chew", "chip", "chop", "cite",
    "clap", "clay", "clip", "club", "clue", "coal", "coat", "code", "coil", "coin", "comb", "cone", "cope", "cord",
    "core", "cork", "corn", "couch", "cram", "crop", "cube", "cure", "curl", "damp", "dare", "dart", "dash", "dawn",
    "daze", "deaf", "dean", "deck", "deed", "deem", "dent", "desk", "dial", "dice", "dine", "dip", "dirt", "dish",
    "disk", "ditch", "dive", "dock", "dome", "dose", "dote", "dove", "dump", "dusk", "dust", "earn", "ease", "echo",
    "emit", "envy", "even", "exam", "fade", "fare", "farm", "fast", "fate", "fawn", "faze", "feed", "feet", "felt",
    "fend", "fern", "flaw", "flex", "flip", "flow", "fond", "font", "fork", "foul", "fray", "fret", "frog", "fume",
    "fuse", "gale", "gall", "gang", "gape", "gear", "germ", "gild", "gist", "glee", "glue", "gone", "gore", "gown",
    "grab", "gram", "grin", "grip", "grit", "grub", "gulf", "gull", "gulp", "hack", "hail", "halt", "harp", "hash",
    "heal", "heap", "heed", "heel", "helm", "hemp", "herb", "herd", "hide", "hill", "hilt", "hint", "hire", "hive",
    "hoax", "hole", "hone", "hook", "horn", "hose", "host", "howl", "hull", "hump", "hurl", "hymn", "icon", "idle",
    "inch", "itch", "jade", "jest", "jolt", "junk", "kick", "knit", "knob", "knot", "lace", "lame", "lamp", "lane",
    "lark", "laze", "leaf", "lean", "leap", "lend", "lens", "lift", "limb", "limp", "link", "lint", "lion", "lore",
    "lure", "lust", "mace", "mail", "mall", "mast", "maze", "melt", "mesh", "mild", "mill", "mist", "mode", "mole",
    "monk", "moon", "mope", "moss", "mull", "mute", "nail", "nape", "nest", "nick", "node", "norm", "numb", "oath",
    "oven", "pace", "pack", "pale", "palm", "pave", "pawn", "peel", "pelt", "perch", "pine", "pink", "pipe", "pity",
    "pond", "pool", "port", "pose", "pour", "pout", "prey", "prop", "prow", "pump", "pyre", "rack", "ramp", "rank",
    "rant", "raze", "reel", "rein", "rend", "rent", "rife", "rift", "ring", "rink", "riot", "roam", "roar", "robe",
    "rock", "rogue", "roll", "romp", "rope", "rose", "rout", "rove", "ruby", "ruse", "rust", "sage", "sail", "sake",
    "salt", "sand", "sash", "scan", "scar", "seam", "sear", "seed", "seep", "self", "sell", "send", "shed", "shin",
    "ship", "shot", "shut", "sift", "silk", "sill", "silt", "sink", "sire", "slab", "slap", "slim", "slip", "slit",
    "slot", "slow", "slug", "snap", "sneak", "snip", "soak", "soar", "sock", "soil", "span", "spar", "sped", "spin",
    "spit", "spew", "spot", "spur", "stab", "stem", "stew", "stir", "stub", "stun", "suck", "suit", "sulk", "swap",
    "tame", "tang", "tape", "tare", "tarp", "taut", "teem", "thin", "thud", "tide", "tier", "tilt", "tint", "tire",
    "toll", "tomb", "tone", "toss", "tour", "tram", "trap", "tray", "trim", "trio", "trot", "tuft", "tusk", "twin",
    "twig", "ugly", "undo", "vain", "vale", "vane", "veer", "vent", "verb", "vest", "veto", "vibe", "vine", "void",
    "wade", "wage", "wail", "wake", "wane", "ward", "ware", "warp", "wart", "wave", "weld", "wend", "whet", "whim",
    "whip", "wick", "wink", "wipe", "wire", "yell", "zeal", "zoom",
    // Extended batch 4
    "ability", "absence", "abstract", "abundant", "academic", "acclaimed", "acknowledge", "acoustic", "activate",
    "adamant", "addicted", "admirable", "adorn", "adversity", "affection", "agitate", "agonize", "agreeable",
    "alarming", "alienate", "alleviate", "allure", "altruistic", "ambiguous", "ambitious", "amiable", "amplify",
    "amusing", "animated", "annihilate", "appealing", "apprehend", "aptitude", "arduous", "aristocrat", "arrogant",
    "articulate", "aspiring", "assertive", "astonish", "attentive", "authentic", "authorize", "awe", "balanced",
    "bankrupt", "bargain", "beguile", "benevolent", "bizarre", "blissful", "boisterous", "boundless", "brilliant",
    "broaden", "capable", "captivate", "careful", "cautious", "charitable", "cheerful", "classic", "clever",
    "colossal", "compassion", "competent", "conceited", "confident", "conscientious", "contemplate", "content",
    "contrite", "controversial", "courageous", "creative", "critical", "cynical", "daunting", "decisive",
    "dedicated", "deliberate", "dependable", "desperate", "determined", "devoted", "dignified", "diligent",
    "diplomatic", "earnest", "eccentric", "educated", "effective", "efficient", "eloquent", "empower", "energetic",
    "engaging", "enlighten", "enthusiastic", "excellent", "exceptional", "exhausting", "exquisite", "faithful",
    "fantastic", "favorable", "fearless", "flexible", "fluent", "formidable", "fortunate", "fragile", "freedom",
    "friendly", "fruitful", "fulfilling", "generous", "gifted", "glorious", "graceful", "grateful", "greedy",
    "harmonious", "helpful", "heroic", "hopeful", "hospitable", "humane", "idealistic", "imaginative", "immaculate",
    "impartial", "impressive", "inclined", "independent", "indispensable", "industrious", "influential",
    "innovative", "insightful", "inspiring", "intelligent", "inventive", "joyful", "judicious", "knowledgeable",
    "lavish", "limitless", "lively", "logical", "magnificent", "masterful", "meaningful", "meticulous", "mindful",
    "motivated", "nurturing", "objective", "optimistic", "organized", "original", "outstanding", "passionate",
    "peaceful", "persistent", "persuasive", "philosophical", "playful", "polite", "practical", "proactive",
    "productive", "progressive", "prominent", "punctual", "rational", "realistic", "reasonable", "receptive",
    "reliable", "remarkable", "resourceful", "respectful", "responsible", "righteous", "sensible", "sincere",
    "skillful", "sociable", "sophisticated", "spirited", "spontaneous", "steadfast", "strategic", "successful",
    "supportive", "talented", "tenacious", "thankful", "thoughtful", "tolerant", "trustworthy", "truthful",
    "understanding", "upbeat", "versatile", "vibrant", "virtuous", "visionary", "vivid", "warm", "welcoming",
    "willing", "wise", "witty"
];

// Build the Set — single source of truth, server-side only
const WORD_LIST = new Set(
    WORDS.map(w => w.toLowerCase().trim()).filter(w => w.length > 3)
);

// Build pair → answers map
// e.g. { "ae": ["able","alive",...], "ak": ["awake",...], ... }
const pairAnswers = {};
for (const word of WORD_LIST) {
    const key = word[0] + word[word.length - 1];
    if (!pairAnswers[key]) pairAnswers[key] = [];
    pairAnswers[key].push(word);
}

const VALID_PAIRS = Object.keys(pairAnswers);

module.exports = { WORD_LIST, pairAnswers, VALID_PAIRS };